# Modelo de Elección Libre: Regresión Logística

## Importación de librerías

In [1]:
import pandas as pd
pd.set_option('display.max_columns', 25) # Número máximo de columnas a mostrar
pd.set_option('display.max_rows', 50) # Numero máximo de filas a mostar
import numpy as np
np.random.seed(3301)
import pandas as pd
# Para preparar los datos
from sklearn.preprocessing import LabelEncoder
# Para crear el arbol de decisión 
from sklearn.tree import DecisionTreeClassifier 
# Para realizar la separación del conjunto de aprendizaje en entrenamiento y test.
from sklearn.model_selection import train_test_split
# Para evaluar el modelo
from sklearn.metrics import confusion_matrix, classification_report, precision_score, recall_score, f1_score, accuracy_score
from sklearn.metrics import plot_confusion_matrix
# Para búsqueda de hiperparámetros
from sklearn.model_selection import GridSearchCV
# Para la validación cruzada
from sklearn.model_selection import KFold 
#Librerías para la visualización
import matplotlib as mplt
import matplotlib.pyplot as plt
# Seaborn
import seaborn as sns 
from sklearn import tree

#Regresion Lineal
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

#Regresion Logistica
from sklearn import metrics 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.stats.weightstats import ttest_ind


## Carga de datos

In [11]:
# Se cargan los datos. 
datos=pd.read_csv('datos.csv', sep=';', encoding = 'utf-8')
datos.head()

,HairColor,Pregnancies,Glucose,City,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,Red,6.0,148.0,New York,72.0,35.0,0.0,336,627.0,50,1.0
1,Black,1.0,85.0,New York,66.0,29.0,0.0,266,351.0,31,0.0
2,Red,8.0,183.0,New York,64.0,0.0,0.0,233,672.0,32,1.0
3,Black,1.0,89.0,New York,66.0,23.0,94.0,281,167.0,21,0.0
4,Black,0.0,137.0,New York,40.0,35.0,168.0,431,2288.0,33,1.0

In [12]:
datos.shape

(768, 11)

In [13]:
# Podemos ver los tipos de todas la variables.
datos.dtypes

HairColor                    object
Pregnancies                 float64
Glucose                     float64
City                         object
BloodPressure               float64
SkinThickness               float64
Insulin                     float64
BMI                           int64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                     float64
dtype: object

In [14]:
# Y hacer una descripción de los datos
datos.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,767.000000,767.000000,767.000000,767.000000,767.000000,768.000000,767.000000,768.000000,767.000000
mean,3.839635,120.921773,69.096480,20.563233,79.903520,289.796875,432.395046,38.011719,0.349413
std,3.368429,31.984561,19.366833,15.945349,115.283105,116.757554,336.144934,117.825600,0.477096
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,251.750000,205.500000,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,32.000000,309.000000,337.000000,29.000000,0.000000
75%,6.000000,140.500000,80.000000,32.000000,127.500000,359.000000,592.000000,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,671.000000,2329.000000,3256.000000,1.000000

In [15]:
# Se observa que hay ausencias:
datos.isnull().sum()

HairColor                   0
Pregnancies                 1
Glucose                     1
City                        1
BloodPressure               1
SkinThickness               1
Insulin                     1
BMI                         0
DiabetesPedigreeFunction    1
Age                         0
Outcome                     1
dtype: int64

### Limpieza

In [16]:
# Es recomendable que todos los pasos de limpieza y preparación se realicen sobre otro archivo.
datoslimpios = datos
datoslimpios

,HairColor,Pregnancies,Glucose,City,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,Red,6.0,148.0,New York,72.0,35.0,0.0,336,627.0,50,1.0
1,Black,1.0,85.0,New York,66.0,29.0,0.0,266,351.0,31,0.0
2,Red,8.0,183.0,New York,64.0,0.0,0.0,233,672.0,32,1.0
3,Black,1.0,89.0,New York,66.0,23.0,94.0,281,167.0,21,0.0
4,Black,0.0,137.0,New York,40.0,35.0,168.0,431,2288.0,33,1.0
...,...,...,...,...,...,...,...,...,...,...,...
763,Black,10.0,101.0,New York,76.0,48.0,180.0,329,171.0,63,0.0
764,Black,2.0,122.0,New York,70.0,27.0,0.0,368,34.0,27,0.0
765,Red,5.0,121.0,New York,72.0,23.0,112.0,262,245.0,30,0.0
766,Black,1.0,126.0,New York,60.0,0.0,0.0,301,349.0,47,1.0
767,Red,1.0,93.0,New York,70.0,31.0,0.0,304,315.0,23,0.0

In [17]:
# Eliminación registros con ausencias
#¿Porqué realizar este paso?
datoslimpios = datoslimpios.dropna()

In [18]:
# Cantidad de datos y número de variables
datoslimpios.shape

(767, 11)

In [19]:
#Restricciones

#Edad menor a 100 y mayor a 21
datoslimpios = datoslimpios[datoslimpios.Age < 100]
datoslimpios = datoslimpios[datoslimpios.Age >= 21]

#BMI no puede ser 0
datoslimpios = datoslimpios[datoslimpios.BMI >0]

#Glucosa no puede ser 0
datoslimpios = datoslimpios[datoslimpios.Glucose >0]

#BloodPressure no puede ser 0
datoslimpios = datoslimpios[datoslimpios.BloodPressure >0]

#SkinThickness no puede ser 0
datoslimpios = datoslimpios[datoslimpios.SkinThickness> 0]

#Quitar color de pelo y ciudad
datoslimpios = datoslimpios.drop(['HairColor'], axis=1)
datoslimpios = datoslimpios.drop(['City'], axis=1)

datoslimpios

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,0.0,336,627.0,50,1.0
1,1.0,85.0,66.0,29.0,0.0,266,351.0,31,0.0
3,1.0,89.0,66.0,23.0,94.0,281,167.0,21,0.0
4,0.0,137.0,40.0,35.0,168.0,431,2288.0,33,1.0
6,3.0,78.0,50.0,32.0,88.0,31,248.0,26,1.0
...,...,...,...,...,...,...,...,...,...
761,9.0,170.0,74.0,31.0,0.0,44,403.0,43,1.0
763,10.0,101.0,76.0,48.0,180.0,329,171.0,63,0.0
764,2.0,122.0,70.0,27.0,0.0,368,34.0,27,0.0
765,5.0,121.0,72.0,23.0,112.0,262,245.0,30,0.0
767,1.0,93.0,70.0,31.0,0.0,304,315.0,23,0.0

## Construcción del modelo

In [20]:
dataX =datoslimpios[["Outcome"]]
X_train = np.array(dataX)
y_train = datoslimpios['BloodPressure'].values
 
# Creamos el objeto de Regresión Linear
regr = linear_model.LinearRegression()
 
# Entrenamos nuestro modelo
regr.fit(X_train, y_train)
 
# Hacemos las predicciones que en definitiva una línea (en este caso, al ser 2D)
y_pred = regr.predict(X_train)
 
# Veamos los coeficienetes obtenidos, En nuestro caso, serán la Tangente
print('Coefficients: \n', regr.coef_)
# Este es el valor donde corta el eje Y (en X=0)
print('Independent term: \n', regr.intercept_)
# Error Cuadrado Medio
print("Mean squared error: %.2f" % mean_squared_error(y_train, y_pred))
# Puntaje de Varianza. El mejor puntaje es un 1.0
print('Variance score: %.2f' % r2_score(y_train, y_pred))

Coefficients:
 [4.77118644]
Independent term:
 69.92937853107344
Mean squared error: 146.38
Variance score: 0.03

In [21]:
modelname="Regresion Logistica"

In [22]:
x = datoslimpios.drop('Outcome',axis = 1)
y = datoslimpios.Outcome

In [23]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=4)

In [24]:
lr = LogisticRegression(solver='lbfgs',max_iter=1000)

In [25]:
lr.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [26]:
y_pred=lr.predict(x_test)

In [27]:
# Información del modelo
# ==============================================================================
print("Intercept:", lr.intercept_)
print("Coeficiente:", list(zip(x.columns, lr.coef_.flatten(), )))
print("Accuracy:", lr.score(x, y))

Intercept: [-8.35224964]
Coeficiente: [('Pregnancies', 0.09182069836319977), ('Glucose', 0.03872006546115016), ('BloodPressure', -0.01073001178542329), ('SkinThickness', 0.04196020347681319), ('Insulin', -0.001102734296002108), ('BMI', 0.001629092633452907), ('DiabetesPedigreeFunction', 0.0015175777755623836), ('Age', 0.02644000069451881)]
Accuracy: 0.7871939736346516

In [28]:
# Predicciones probabilísticas
# ==============================================================================
# Con .predict_proba() se obtiene, para cada observación, la probabilidad predicha
# de pertenecer a cada una de las dos clases.
predicciones = lr.predict_proba( x_test)
predicciones = pd.DataFrame(predicciones, columns = lr.classes_)
predicciones.head(5)

        0.0       1.0
0  0.833033  0.166967
1  0.473742  0.526258
2  0.955244  0.044756
3  0.842796  0.157204
4  0.587502  0.412498

In [29]:
# Creación del modelo utilizando matrices como en scikitlearn
# ==============================================================================
# A la matriz de predictores se le tiene que añadir una columna de 1s para el intercept del modelo
x_train = sm.add_constant(x_train, prepend=True)
lr = sm.Logit(endog=y_train, exog=x_train,)
lr = lr.fit()
print(lr.summary())

Optimization terminated successfully.
         Current function value: 0.442070
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                Outcome   No. Observations:                  398
Model:                          Logit   Df Residuals:                      389
Method:                           MLE   Df Model:                            8
Date:                Fri, 03 Sep 2021   Pseudo R-squ.:                  0.3023
Time:                        13:58:44   Log-Likelihood:                -175.94
converged:                       True   LL-Null:                       -252.16
Covariance Type:            nonrobust   LLR p-value:                 6.084e-29
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                       -8.3515      1.040     -8.030      0.000     -10.390      -6.313
Pregnancies                  0.0920      0.050      1.832      0.067      -0.006       0.190
Glucose                      0.0387      0.005      7.080      0.000       0.028       0.049
BloodPressure               -0.0107      0.012     -0.918      0.359      -0.034       0.012
SkinThickness                0.0420      0.015      2.811      0.005       0.013       0.071
Insulin                     -0.0011      0.001     -0.948      0.343      -0.003       0.001
BMI                          0.0016      0.001      1.160      0.246      -0.001       0.004
DiabetesPedigreeFunction     0.0015      0.000      3.736      0.000       0.001       0.002
Age                          0.0264      0.016      1.657      0.097      -0.005       0.058
============================================================================================

In [30]:
# Intervalos de confianza para los coeficientes del modelo
# ==============================================================================
intervalos_ci = lr.conf_int(alpha=0.05)
intervalos_ci = pd.DataFrame(intervalos_ci)
intervalos_ci.columns = ['2.5%', '97.5%']
intervalos_ci

                               2.5%     97.5%
const                    -10.390024 -6.313075
Pregnancies               -0.006428  0.190482
Glucose                    0.028003  0.049441
BloodPressure             -0.033633  0.012177
SkinThickness              0.012705  0.071200
Insulin                   -0.003383  0.001176
BMI                       -0.001123  0.004381
DiabetesPedigreeFunction   0.000721  0.002314
Age                       -0.004824  0.057614